name: app

packages: 
  - /**

scripts:
  test_cov:
    run: melos exec -c 1 --dir-exists="test" --fail-fast -- flutter test --coverage
    description: Run tests on packages that contains test folder and generate coverage
    
  union_cov:
    run: melos exec -c 1 -- "\$MELOS_ROOT_PATH/combine_coverage.sh"
    description: merge lcov files from packages into a single file at the root